language: go

sudo: false

go:
  - 1.15

before_install:
  - go get ${gobuild_args} ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=coverage.out -coverpkg=./,./plm,./util,./cmd/... ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
