language: go

sudo: false

go:
  - master

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=coverage.out -coverpkg=./,./plm,./link,./cmd/... ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
