// Code generated by "stringer -type=Command -linecomment=true"; DO NOT EDIT.

package insteon

import "strconv"

const _Command_name = "Set-button Pressed (responder)Set-button Pressed (controller)Test Powerline PhaseFx Username RequestText String RequestSet Text StringHeartbeatAll-link Cleanup ReportExit Linking ModeEnter Linking-modeEnter Unlinking-modeEngine VersionPing RequestID RequestAll-link recallCmdLightOnAll-link Alias 2 HighAll-link Alias 1 LowAll-link Alias 2 LowAll-link Alias 3 HighAll-link Alias 3 LowAll-link Alias 4 HighAll-link Alias 4 LowCmdLightStatusRequestGet Operating FlagsSet Operating FlagsAll-link Alias 5CmdLightManualOnCmdLightManualOffCmdTapSetButtonOnceCmdTapSetButtonTwiceBroadcast Status ChangeCmdLightOnAtRampRead/Write ALDBCmdLightOnAtRampV67CmdLightOffAtRampV67"

var _Command_map = map[Command]string{
	256:   _Command_name[0:30],
	512:   _Command_name[30:61],
	768:   _Command_name[61:81],
	769:   _Command_name[81:100],
	770:   _Command_name[100:119],
	771:   _Command_name[119:134],
	1024:  _Command_name[134:143],
	1536:  _Command_name[143:166],
	2048:  _Command_name[166:183],
	2304:  _Command_name[183:201],
	2560:  _Command_name[201:221],
	3328:  _Command_name[221:235],
	3840:  _Command_name[235:247],
	4096:  _Command_name[247:257],
	4352:  _Command_name[257:272],
	4607:  _Command_name[272:282],
	4608:  _Command_name[282:303],
	4864:  _Command_name[303:323],
	5120:  _Command_name[323:343],
	5376:  _Command_name[343:364],
	5632:  _Command_name[364:384],
	5888:  _Command_name[384:405],
	6144:  _Command_name[405:425],
	6400:  _Command_name[425:446],
	7936:  _Command_name[446:465],
	8192:  _Command_name[465:484],
	8448:  _Command_name[484:500],
	8705:  _Command_name[500:516],
	8961:  _Command_name[516:533],
	9473:  _Command_name[533:552],
	9474:  _Command_name[552:572],
	9984:  _Command_name[572:595],
	11776: _Command_name[595:611],
	12032: _Command_name[611:626],
	13312: _Command_name[626:645],
	13568: _Command_name[645:665],
}

func (i Command) String() string {
	if str, ok := _Command_map[i]; ok {
		return str
	}
	return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
}
