// Code generated by "stringer -type=ThermostatMode,Unit,FanSpeed -linecomment"; DO NOT EDIT.

package insteon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ThermostatOff-0]
	_ = x[Heat-1]
	_ = x[Cool-2]
	_ = x[Auto-3]
	_ = x[FanOn-4]
	_ = x[ProgramAuto-5]
	_ = x[ProgramHeat-6]
	_ = x[ProgramCool-7]
	_ = x[FanOff-8]
}

const _ThermostatMode_name = "Thermostat OffHeat ModeCool ModeAuto ModeFan OnProgram AutoProgram HeatProgram CoolFan Off"

var _ThermostatMode_index = [...]uint8{0, 14, 23, 32, 41, 47, 59, 71, 83, 90}

func (i ThermostatMode) String() string {
	if i >= ThermostatMode(len(_ThermostatMode_index)-1) {
		return "ThermostatMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ThermostatMode_name[_ThermostatMode_index[i]:_ThermostatMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fahrenheit-0]
	_ = x[Celsius-1]
}

const _Unit_name = "°F°C"

var _Unit_index = [...]uint8{0, 3, 6}

func (i Unit) String() string {
	if i < 0 || i >= Unit(len(_Unit_index)-1) {
		return "Unit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Unit_name[_Unit_index[i]:_Unit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SingleSpeed-0]
	_ = x[LowSpeed-1]
	_ = x[MedSpeed-2]
	_ = x[HighSpeed-3]
}

const _FanSpeed_name = "Single SpeedLow SpeedMedium SpeedHigh Speed"

var _FanSpeed_index = [...]uint8{0, 12, 21, 33, 43}

func (i FanSpeed) String() string {
	if i < 0 || i >= FanSpeed(len(_FanSpeed_index)-1) {
		return "FanSpeed(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FanSpeed_name[_FanSpeed_index[i]:_FanSpeed_index[i+1]]
}
